### Get Recommendations ###
GET https://api.spotify.com/v1/recommendations?seed_tracks=0c6xIDDpzE81m2q797ordA,6nTiIhLmQ3FWhvrGafw2zj&seed_genres=morrocanRap&seed_artists=4BFLElxtBEdsdwGA1kHTsx
Authorization: Bearer BQAJICgvL8ueYE0hwcfShGTsNSRt4wEWyNaOCgANifDen7s3pJ3V4-0WaRYqsjdbz4NVw05vpBZZSyWUziHn3_mQ74uWAIKtsPhnfJ_4W0tWZiEgpWw


####
GET https://api.spotify.com/v1/recommendations/available-genre-seeds
Authorization: Bearer BQAJICgvL8ueYE0hwcfShGTsNSRt4wEWyNaOCgANifDen7s3pJ3V4-0WaRYqsjdbz4NVw05vpBZZSyWUziHn3_mQ74uWAIKtsPhnfJ_4W0tWZiEgpWw


####
GET https://api.spotify.com/v1/recommendations/available-genre-seeds
Authorization: Bearer BQAJICgvL8ueYE0hwcfShGTsNSRt4wEWyNaOCgANifDen7s3pJ3V4-0WaRYqsjdbz4NVw05vpBZZSyWUziHn3_mQ74uWAIKtsPhnfJ_4W0tWZiEgpWw


###?# artist
get https://api.spotify.com/v1/search?q=artist:elgrande%20toto&type=artist
Authorization: Bearer BQAJICgvL8ueYE0hwcfShGTsNSRt4wEWyNaOCgANifDen7s3pJ3V4-0WaRYqsjdbz4NVw05vpBZZSyWUziHn3_mQ74uWAIKtsPhnfJ_4W0tWZiEgpWw

####genre 

get https://api.spotify.com/v1/search?q=genre:pop&type=genres
Authorization: Bearer BQAJICgvL8ueYE0hwcfShGTsNSRt4wEWyNaOCgANifDen7s3pJ3V4-0WaRYqsjdbz4NVw05vpBZZSyWUziHn3_mQ74uWAIKtsPhnfJ_4W0tWZiEgpWw

####album

get https://api.spotify.com/v1/search?q=album:certified%20lover%20boy&type=album
Authorization: Bearer BQAJICgvL8ueYE0hwcfShGTsNSRt4wEWyNaOCgANifDen7s3pJ3V4-0WaRYqsjdbz4NVw05vpBZZSyWUziHn3_mQ74uWAIKtsPhnfJ_4W0tWZiEgpWw

